# Generated by Django 2.1.7 on 2019-03-05 06:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='total_votes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='total_votes',
        ),
    ]
