# Generated by Django 2.1.5 on 2019-02-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_auto_20190208_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='简介'),
        ),
    ]
